db:
  image: mongo
  volumes:
     - ./data/runtime/db:/data/db
     - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:develop
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - ROOT_URL=http://rocket-chat.kicks-ass.org
    - MONGO_URL=mongodb://db:27017/rocketchat
# uncomment and set the line below if you need to support mobile apps
#   - DDP_DEFAULT_CONNECTION_URL=http://yourhost:3000
  links:
    - db:db
  ports:
    - 80:3000
